import pytest
from pathlib import Path
from src.rag.formatter import DigestFormatter

def test_formatter_save_and_extract(tmp_path):
    # tmp_path is a built-in pytest fixture for a temporary directory
    formatter = DigestFormatter(output_dir=str(tmp_path))
    
    raw_markdown = """# AI News Pulse - 2026-07-20
This is a great executive summary.
It spans two lines for testing.

## 🤖 LLMs & Foundational Models
This content should not be in the summary.
"""
    
    payload = formatter.format_and_save(raw_markdown, "2026-07-20")
    
    # 1. Verify JSON payload structure
    assert payload["date"] == "2026-07-20"
    assert "This is a great executive summary. It spans two lines for testing." == payload["executive_summary"]
    assert payload["full_markdown"] == raw_markdown
    
    # 2. Verify file was saved correctly to disk
    saved_file = Path(payload["file_path"])
    assert saved_file.exists()
    assert saved_file.read_text(encoding="utf-8") == raw_markdown

def test_formatter_no_summary(tmp_path):
    formatter = DigestFormatter(output_dir=str(tmp_path))
    
    # Edge case: No summary provided by LLM before headings
    raw_markdown = """# AI News Pulse - 2026-07-21
## 🤖 LLMs & Foundational Models
Content jumped straight to heading.
"""
    
    payload = formatter.format_and_save(raw_markdown, "2026-07-21")
    
    assert payload["executive_summary"] == "Daily AI news digest generated by AI News Pulse."
