import json
import logging
from pathlib import Path
from typing import Dict, Any

logger = logging.getLogger(__name__)

class DigestFormatter:
    def __init__(self, output_dir: str = "data/digests"):
        """Initializes the formatter and ensures the local output directory exists."""
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def format_and_save(self, raw_markdown: str, target_date: str) -> Dict[str, Any]:
        """
        Saves the raw markdown output from the LLM to disk for local archiving, 
        and extracts a structured JSON payload (including an executive summary) 
        that will be inserted into PostgreSQL for the FastAPI backend to serve.
        """
        logger.info(f"Formatting and saving digest for {target_date}...")
        
        # 1. Save Markdown File locally
        md_filename = self.output_dir / f"digest_{target_date}.md"
        try:
            with open(md_filename, "w", encoding="utf-8") as f:
                f.write(raw_markdown)
            logger.info(f"Saved Markdown digest to {md_filename}")
        except Exception as e:
            logger.error(f"Failed to save Markdown digest to disk: {e}")
            raise

        # 2. Parse the Markdown to extract the Executive Summary for the database
        lines = raw_markdown.split('\n')
        summary_lines = []
        capture_summary = False
        
        for line in lines:
            # Skip the main H1 title block
            if line.startswith("# AI News Pulse"):
                capture_summary = True
                continue
            # Stop capturing when we hit the first H2 category heading
            if line.startswith("## "):
                break
                
            # Grab any non-empty lines right after the title
            if capture_summary and line.strip():
                summary_lines.append(line.strip())
                
        executive_summary = " ".join(summary_lines)
        if not executive_summary:
            executive_summary = "Daily AI news digest generated by AI News Pulse."

        # 3. Return the structured payload for the orchestrator to store in PostgreSQL
        structured_data = {
            "date": target_date,
            "executive_summary": executive_summary,
            "full_markdown": raw_markdown,
            "file_path": str(md_filename)
        }
        
        return structured_data
